// next/src/components/shared/result-table.tsx
"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";
import { Copy, Download } from "lucide-react";
import { toast } from "sonner";

interface ResultTableProps {
  columns: { name: string; type: string }[];
  rows: Record<string, string>[];
  maxRows?: number;
  className?: string;
}

export function ResultTable({
  columns,
  rows,
  maxRows = 100,
  className,
}: ResultTableProps) {
  const [expanded, setExpanded] = useState(false);
  const displayRows = expanded ? rows : rows.slice(0, maxRows);
  const hasMore = rows.length > maxRows;

  const handleCopyCell = (value: string) => {
    navigator.clipboard.writeText(value);
    toast.success("Copied to clipboard");
  };

  const handleExportCSV = () => {
    const header = columns.map((c) => c.name).join(",");
    const csvRows = rows.map((r) =>
      columns.map((c) => `"${(r[c.name] || "").replace(/"/g, '""')}"`).join(",")
    );
    const csv = [header, ...csvRows].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "export.csv";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={cn("space-y-2", className)}>
      <div className="flex items-center justify-between">
        <span className="text-sm text-muted-foreground">
          {rows.length} row{rows.length !== 1 ? "s" : ""}
        </span>
        <button
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 hover:bg-accent hover:text-accent-foreground h-8 rounded-md px-3 text-xs"
          onClick={handleExportCSV}
        >
          <Download className="h-3 w-3 mr-1" />
          CSV
        </button>
      </div>
      <div className="overflow-x-auto rounded-md border">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b bg-muted/50">
              {columns.map((col) => (
                <th
                  key={col.name}
                  className="px-3 py-2 text-left font-medium text-muted-foreground whitespace-nowrap"
                >
                  {col.name}
                  <span className="ml-1 text-xs text-muted-foreground/60">
                    {col.type}
                  </span>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {displayRows.map((row, i) => (
              <tr
                key={i}
                className="border-b last:border-0 hover:bg-muted/30"
              >
                {columns.map((col) => (
                  <td
                    key={col.name}
                    className="px-3 py-2 max-w-[300px] truncate cursor-pointer hover:bg-accent/50"
                    onClick={() => handleCopyCell(row[col.name] || "")}
                    title={row[col.name]}
                  >
                    {row[col.name] || "—"}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {hasMore && (
        <button
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 hover:bg-accent hover:text-accent-foreground h-8 rounded-md px-3 text-xs w-full"
          onClick={() => setExpanded(!expanded)}
        >
          {expanded
            ? "Show less"
            : `Show all ${rows.length} rows (${rows.length - maxRows} more)`}
        </button>
      )}
    </div>
  );
}

// frontend/src/lib/components/ui/ResultTable.svelte
<script lang="ts">
  import LL from "$lib/i18n/i18n-svelte";
  let {
    columns,
    rows,
    max = 8,
  }: { columns: string[]; rows: string[][]; max?: number } = $props();
  let copied = $state(false);
  let copiedTimer: ReturnType<typeof setTimeout> | undefined;
  let copiedCell: string | null = $state(null);
  let copiedCellTimer: ReturnType<typeof setTimeout> | undefined;

  function copyCell(text: string) {
    const fallback = () => {
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      try { document.execCommand("copy"); } finally { document.body.removeChild(ta); }
    };
    if (navigator.clipboard?.writeText) {
      navigator.clipboard.writeText(text).catch(() => fallback());
    } else {
      fallback();
    }
    copiedCell = text;
    clearTimeout(copiedCellTimer);
    copiedCellTimer = setTimeout(() => (copiedCell = null), 800);
  }

  function isNumeric(v: string): boolean {
    return typeof v === "string" && /^[$]?[\d.,%]+$/.test(v);
  }

  function copyCSV() {
    const cell = (v: string) => {
      let s = String(v ?? "");
      if (/[\s\x00-\x1f]*[=+\-@]/.test(s)) s = "'" + s;
      return s.includes(",") || s.includes('"') || s.includes("\n")
        ? `"${s.replace(/"/g, '""')}"`
        : s;
    };
    const header = columns.map(cell).join(",");
    const body = rows.map((r) => r.map(cell).join(",")).join("\n");
    const csv = header + "\n" + body;
    const fallback = () => {
      const ta = document.createElement("textarea");
      ta.value = csv;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      try {
        const success = document.execCommand("copy");
        if (success) {
          copied = true;
          clearTimeout(copiedTimer);
          copiedTimer = setTimeout(() => (copied = false), 2000);
        }
      } finally {
        document.body.removeChild(ta);
      }
    };
    if (navigator.clipboard?.writeText) {
      navigator.clipboard
        .writeText(csv)
        .then(() => {
          copied = true;
          clearTimeout(copiedTimer);
          copiedTimer = setTimeout(() => (copied = false), 2000);
        })
        .catch(() => {
          fallback();
        });
      return;
    }
    fallback();
  }
</script>

{#if !rows || rows.length === 0}
  <div
    style="padding:22px 18px;text-align:center;color:var(--muted);background:var(--surface-2);border:1px dashed var(--border-2);border-radius:var(--radius);font-size:14px"
  >
    {$LL.chat.noRowsMatched()}
  </div>
{:else}
  <div
    style="border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;background:var(--surface)"
  >
    <div
      style="display:flex;align-items:center;justify-content:space-between;padding:7px 12px 0;background:var(--surface-2);border-bottom:1px solid var(--border)"
    >
      <span style="font-size:11.5px;font-weight:600;color:var(--faint)">{$LL.chat.rowsReturned({n: rows.length})}</span>
      <button
        onclick={copyCSV}
        title={$LL.chat.copyCsvTitle()}
        aria-live="polite"
        class="tb-btn"
        style="display:inline-flex;align-items:center;gap:4px;padding:4px 8px;font-size:11.5px;font-weight:650;color:{copied
          ? 'var(--brand)'
          : 'var(--faint)'}"
      >
        {copied ? $LL.chat.copiedCsv() : $LL.chat.copyCsv()}
      </button>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:14px">
      <thead>
        <tr>
          {#each columns as c}
            <th
              style="text-align:left;padding:11px 16px;font-weight:700;font-size:11.5px;letter-spacing:.06em;text-transform:uppercase;color:var(--faint);background:var(--surface-2);border-bottom:1px solid var(--border)"
              >{c}</th
            >
          {/each}
        </tr>
      </thead>
      <tbody>
        {#each rows.slice(0, max) as r, ri}
          <tr
            style="border-bottom:{ri < rows.length - 1
              ? '1px solid var(--border)'
              : 'none'}"
          >
            {#each r as cell, ci}
              <td
                class={ci > 0 && isNumeric(cell) ? "tnum" : ""}
                onclick={() => copyCell(cell)}
                style="cursor:pointer;padding:11px 16px;color:{ci === 0
                  ? 'var(--ink)'
                  : 'var(--ink-2)'};font-weight:{ci === 0
                  ? 600
                  : 500};font-family:{ci > 0 && isNumeric(cell)
                  ? 'var(--font-mono)'
                  : 'inherit'};text-align:{ci > 0 && isNumeric(cell)
                  ? 'right'
                  : 'left'};font-size:{ci > 0 && isNumeric(cell)
                  ? '13.5px'
                  : '14px'};position:relative"
              >{cell}{#if copiedCell === cell}<span style="position:absolute;top:-4px;right:-4px;font-size:9px;font-weight:700;color:var(--brand);background:var(--surface);padding:0 3px;border-radius:3px;white-space:nowrap">{$LL.chat.copied()}</span>{/if}</td
              >
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}

<style>
  .tb-btn {
    border-radius: 4px;
    border: none;
    background: transparent;
    cursor: pointer;
    transition: color .15s;
  }
  .tb-btn:hover {
    color: var(--muted) !important;
  }
</style>
