// next/src/components/dashboard/table-usage-bar.tsx
"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";
import { CHART_COLORS } from "@/lib/chart-utils";

interface TableUsageBarProps {
  data: { table: string; count: number }[];
}

export function TableUsageBar({ data }: TableUsageBarProps) {
  const chartData = data
    .slice(0, 8)
    .map((d) => ({ ...d, label: d.table }));

  if (chartData.length === 0) {
    return (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: 180,
        }}
      >
        <span style={{ fontSize: 13, fontWeight: 600, color: "var(--faint)" }}>
          No table usage data
        </span>
      </div>
    );
  }

  return (
    <div style={{ height: Math.max(120, chartData.length * 36) }}>
      <ResponsiveContainer width="100%" height="100%">
        <BarChart
          data={chartData}
          layout="vertical"
          margin={{ left: 60, right: 16, top: 4, bottom: 4 }}
        >
          <CartesianGrid
            stroke="var(--border-2)"
            strokeDasharray="3 3"
            horizontal={false}
          />
          <XAxis type="number" tick={{ fontSize: 11, fill: "var(--muted)" }} stroke="var(--border-2)" />
          <YAxis
            type="category"
            dataKey="label"
            tick={{ fontSize: 12, fill: "var(--ink)" }}
            stroke="var(--border-2)"
            tickFormatter={(v: string) =>
              v.length > 16 ? v.slice(0, 16) + "…" : v
            }
            width={56}
          />
          <Tooltip
            contentStyle={{
              background: "var(--surface)",
              border: "1px solid var(--border)",
              borderRadius: 8,
              fontSize: 13,
            }}
          />
          <Bar
            dataKey="count"
            radius={[0, 4, 4, 0]}
            barSize={20}
          >
            {chartData.map((_, i) => (
              <rect
                key={i}
                fill={CHART_COLORS[i % CHART_COLORS.length]}
              />
            ))}
          </Bar>
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}

// frontend/src/lib/components/charts/TableUsageBar.svelte
<script lang="ts">
  import { BarChart } from 'layerchart';
  import { CHART_COLORS } from './chartUtils';

  let {
    data,
  }: {
    data: { table: string; count: number }[];
  } = $props();

  const chartData = $derived(
    data.slice(0, 8).map((d) => ({
      ...d,
      label: d.table.length > 18 ? d.table.slice(0, 16) + '…' : d.table,
    })),
  );
</script>

{#if chartData.length === 0}
  <div style="display:flex;align-items:center;justify-content:center;height:180px;">
    <span style="font-size:13px;font-weight:600;color:var(--faint);">No table usage data</span>
  </div>
{:else}
  <div style="height:{Math.max(120, chartData.length * 36)}px;">
    <BarChart
      data={chartData}
      x="count"
      y="label"
      orientation="horizontal"
      c="label"
      cRange={CHART_COLORS}
      bandPadding={0.3}
      padding={{ left: 10, right: 16, top: 4, bottom: 4 }}
      tooltipContext={{ mode: 'band' }}
      grid={{ y: false }}
    />
  </div>
{/if}
