// next/src/app/(marketing)/page.tsx
"use client";

import { useEffect } from "react";
import { trackSectionView } from "@/lib/marketing/analytics";
import { Backdrop } from "@/components/marketing/backdrop";
import { Hero } from "@/components/marketing/hero";
import { LiveDemo } from "@/components/marketing/live-demo";
import { Pipeline } from "@/components/marketing/pipeline";
import { TrustEngine } from "@/components/marketing/trust-engine";
import { Flywheel } from "@/components/marketing/flywheel";
import { Integrations } from "@/components/marketing/integrations";
import { FinalCta } from "@/components/marketing/final-cta";

const SECTIONS = [
  { id: "hero", section: "hero", Component: Hero },
  { id: "demo", section: "demo", Component: LiveDemo },
  { id: "pipeline", section: "pipeline", Component: Pipeline },
  { id: "trust", section: "trust", Component: TrustEngine },
  { id: "flywheel", section: "flywheel", Component: Flywheel },
  { id: "integrations", section: "integrations", Component: Integrations },
  { id: "cta", section: "cta", Component: FinalCta },
];

export default function MarketingPage() {
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            const section = entry.target.getAttribute("data-section");
            if (section) trackSectionView(section as any);
          }
        });
      },
      { threshold: 0.3 },
    );

    const elements = document.querySelectorAll("[data-section]");
    elements.forEach((el) => observer.observe(el));

    return () => observer.disconnect();
  }, []);

  return (
    <>
      <Backdrop />
      {SECTIONS.map(({ id, section, Component }) => (
        <div key={id} id={id} data-section={section}>
          <Component />
        </div>
      ))}
    </>
  );
}

// frontend/src/routes/(marketing)/+page.svelte
<script lang="ts">
  import { browser } from "$app/environment";
  import { trackSectionView } from "$lib/marketing/analytics";
  import Backdrop from "$lib/marketing/Backdrop.svelte";
  import Hero from "$lib/marketing/Hero.svelte";
  import LiveDemo from "$lib/marketing/LiveDemo.svelte";
  import Pipeline from "$lib/marketing/Pipeline.svelte";
  import TrustEngine from "$lib/marketing/TrustEngine.svelte";
  import Flywheel from "$lib/marketing/Flywheel.svelte";
  import Integrations from "$lib/marketing/Integrations.svelte";
  import FinalCta from "$lib/marketing/FinalCta.svelte";

  const sections = ["hero", "demo", "pipeline", "trust", "flywheel", "integrations", "cta"] as const;

  $effect(() => {
    if (!browser) return;
    const obs = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            const id = e.target.getAttribute("data-section");
            if (id) trackSectionView(id as any);
          }
        }
      },
      { threshold: 0.3 }
    );

    for (const id of sections) {
      const el = document.getElementById(id);
      if (el) obs.observe(el);
    }

    return () => obs.disconnect();
  });
</script>

<svelte:head>
  <title>BoloDB — Talk to your database like a human.</title>
  <meta name="description" content="Ask questions in plain English, get instant answers, and trust the logic with our verifiable AI engine." />
  <meta property="og:title" content="BoloDB — Talk to your database like a human." />
  <meta property="og:description" content="No SQL required. Ask questions in plain English, get instant answers, and trust the logic with our verifiable AI engine." />
  <meta property="og:type" content="website" />
  <link rel="canonical" href="https://bolodb.com/" />
  <meta name="twitter:card" content="summary_large_image" />
</svelte:head>

<Backdrop />
<div id="hero" data-section="hero"><Hero /></div>
<div id="demo" data-section="demo"><LiveDemo /></div>
<div id="pipeline" data-section="pipeline"><Pipeline /></div>
<div id="trust" data-section="trust"><TrustEngine /></div>
<div id="flywheel" data-section="flywheel"><Flywheel /></div>
<div id="integrations" data-section="integrations"><Integrations /></div>
<div id="cta" data-section="cta"><FinalCta /></div>
