// frontend/src/lib/marketing/Hero.svelte
<script lang="ts">
  import { browser } from "$app/environment";
  import LL from "$lib/i18n/i18n-svelte";
  import { goto } from "$app/navigation";
  import { magnetic } from "$lib/actions/magnetic";
  import { motionPrefs } from "$lib/motion/motionPrefs";
  import { scrollTo } from "$lib/motion/lenis";
  import { trackCtaClick } from "$lib/marketing/analytics";

  let heroEl: HTMLElement;
  let h1Line1: HTMLElement;
  let h1Line2: HTMLElement;
  let subEl: HTMLElement;
  let ctaRow: HTMLElement;
  let trustEl: HTMLElement;

  $effect(() => {
    if (!browser) return;
    if (motionPrefs.reduced) {
      if (h1Line1) h1Line1.style.clipPath = "none";
      if (h1Line2) h1Line2.style.clipPath = "none";
      if (subEl) subEl.style.opacity = "1";
      if (ctaRow) ctaRow.style.opacity = "1";
      if (trustEl) trustEl.style.opacity = "1";
      return;
    }

    let cleanup = () => {};

    (async () => {
      const { loadGsap } = await import("$lib/motion/gsap");
      const { gsap } = await loadGsap();

      const tl = gsap.timeline({ defaults: { ease: "power3.out", duration: 0.6 } });

      tl.fromTo(
        h1Line1,
        { clipPath: "inset(0 0 100% 0)" },
        { clipPath: "inset(0 0 0% 0)", duration: 0.7 }
      )
        .fromTo(
          h1Line2,
          { clipPath: "inset(0 0 100% 0)" },
          { clipPath: "inset(0 0 0% 0)", duration: 0.7 },
          "-=0.4"
        )
        .fromTo(
          subEl,
          { y: 16, opacity: 0 },
          { y: 0, opacity: 1, duration: 0.5 },
          "-=0.25"
        )
        .fromTo(
          ctaRow,
          { y: 16, opacity: 0 },
          { y: 0, opacity: 1, duration: 0.5 },
          "-=0.2"
        )
        .fromTo(
          trustEl,
          { y: 12, opacity: 0 },
          { y: 0, opacity: 1, duration: 0.5 },
          "-=0.15"
        );

      cleanup = () => tl.kill();
    })();

    return () => cleanup();
  });
</script>

<section bind:this={heroEl} class="hero">
  <div class="hero-content">
    <span class="eyebrow">AI data analyst you can trust</span>

    <h1 class="hero-h1">
      <span class="h1-mask" bind:this={h1Line1}><span class="h1-line">{$LL.landing.talkToYourDatabase()}</span></span>
      <span class="h1-mask" bind:this={h1Line2}><span class="h1-line h1-accent">{$LL.landing.likeAHuman()}</span></span>
    </h1>

    <p class="hero-sub" bind:this={subEl}>{$LL.landing.noSqlRequired()}</p>

    <div class="hero-ctas" bind:this={ctaRow}>
      <button
        class="btn btn-primary btn-lg"
        use:magnetic
        onclick={() => { trackCtaClick("hero", "Start for free", "/signup"); goto("/signup"); }}
      >
        {$LL.landing.startForFree()}
      </button>
      <button
        class="btn btn-ghost btn-lg"
        onclick={() => { trackCtaClick("hero", "Watch it work", "#demo"); scrollTo("demo"); }}
      >
        {$LL.landing.viewDemo()}
      </button>
    </div>

    <div class="trust-strip" bind:this={trustEl}>
      <div class="db-logos">
        <span class="db-logo">PostgreSQL</span>
        <span class="db-dot">•</span>
        <span class="db-logo">MySQL</span>
        <span class="db-dot">•</span>
        <span class="db-logo">SQL Server</span>
        <span class="db-dot">•</span>
        <span class="db-logo">SQLite</span>
      </div>
      <span class="trust-line">read-only • your data stays yours</span>
    </div>
  </div>
</section>

<style>
  .hero {
    position: relative;
    z-index: 2;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 90vh;
    padding: 160px 24px 80px;
  }

  .hero-content {
    max-width: 800px;
    text-align: center;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 24px;
  }

  .eyebrow {
    display: inline-flex;
    padding: 6px 14px;
    border-radius: 99px;
    font-size: 13px;
    font-weight: 600;
    color: var(--brand);
    background: var(--brand-tint);
    border: 1px solid var(--brand-tint-2);
    letter-spacing: -0.01em;
  }

  .hero-h1 {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .h1-mask {
    overflow: hidden;
    display: block;
  }

  .h1-line {
    display: block;
    font-size: clamp(2.5rem, 6vw, 4.75rem);
    font-weight: 800;
    line-height: 1.05;
    letter-spacing: -0.02em;
    color: var(--ink);
  }

  .h1-accent {
    color: var(--brand);
  }

  .hero-sub {
    font-size: clamp(1rem, 2vw, 1.25rem);
    line-height: 1.6;
    color: var(--muted);
    max-width: 600px;
    text-wrap: balance;
  }

  .hero-ctas {
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 8px;
  }

  .trust-strip {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 12px;
    margin-top: 32px;
    opacity: 0.7;
  }

  .db-logos {
    display: flex;
    align-items: center;
    gap: 12px;
    font-size: 13px;
    font-weight: 600;
    color: var(--faint);
    font-family: var(--font-mono);
  }

  .db-dot {
    opacity: 0.3;
  }

  .trust-line {
    font-size: 12.5px;
    color: var(--faint);
    letter-spacing: 0.02em;
  }
</style>

// next/src/components/marketing/hero.tsx
"use client";

import { useEffect, useRef } from "react";
import { loadGsap } from "@/lib/motion/gsap";
import { scrollTo } from "@/lib/motion/lenis";
import { trackCtaClick } from "@/lib/marketing/analytics";
import { motionPrefs } from "@/lib/motion/motion-prefs";

export function Hero() {
  const heroEl = useRef<HTMLElement>(null);
  const eyebrowEl = useRef<HTMLSpanElement>(null);
  const h1Line1 = useRef<HTMLSpanElement>(null);
  const h1Line2 = useRef<HTMLSpanElement>(null);
  const subEl = useRef<HTMLParagraphElement>(null);
  const ctaRow = useRef<HTMLDivElement>(null);
  const trustEl = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const els = [eyebrowEl, h1Line1, h1Line2, subEl, ctaRow, trustEl];

    if (motionPrefs.reduced) {
      els.forEach((ref) => {
        if (ref.current) {
          ref.current.style.opacity = "1";
          ref.current.style.clipPath = "none";
        }
      });
      return;
    }

    const safetyTimer = setTimeout(() => {
      els.forEach((ref) => {
        if (ref.current) {
          ref.current.style.opacity = "1";
          ref.current.style.clipPath = "none";
        }
      });
    }, 1500);

    let tl: gsap.core.Timeline | null = null;

    const init = async () => {
      const { gsap } = await loadGsap();
      tl = gsap.timeline();

      if (eyebrowEl.current) {
        tl!.fromTo(
          eyebrowEl.current,
          { y: 10, opacity: 0 },
          { y: 0, opacity: 1, duration: 0.4 }
        );
      }

      if (h1Line1.current) {
        tl!.fromTo(
          h1Line1.current,
          { clipPath: "inset(0 0 100% 0)" },
          { clipPath: "inset(0 0 0% 0)", duration: 0.7 }
        );
      }

      if (h1Line2.current) {
        tl!.fromTo(
          h1Line2.current,
          { clipPath: "inset(0 0 100% 0)" },
          { clipPath: "inset(0 0 0% 0)", duration: 0.7 },
          "-=0.4"
        );
      }

      if (subEl.current) {
        tl!.fromTo(
          subEl.current,
          { y: 16, opacity: 0 },
          { y: 0, opacity: 1, duration: 0.5 },
          "-=0.25"
        );
      }

      if (ctaRow.current) {
        tl!.fromTo(
          ctaRow.current,
          { y: 16, opacity: 0 },
          { y: 0, opacity: 1, duration: 0.5 },
          "-=0.2"
        );
      }

      if (trustEl.current) {
        tl!.fromTo(
          trustEl.current,
          { y: 12, opacity: 0 },
          { y: 0, opacity: 1, duration: 0.5 },
          "-=0.15"
        );
      }
    };

    init();

    return () => {
      clearTimeout(safetyTimer);
      if (tl) tl.kill();
    };
  }, []);

  return (
    <section className="hero" ref={heroEl}>
      <div className="hero-grid">
        <div className="hero-text">
          <span className="hero-eyebrow" ref={eyebrowEl}>BoloDB — Text-to-SQL you can trust</span>
          <h1 className="hero-h1">
            <span className="h1-mask"><span className="h1-line" ref={h1Line1}>Talk to your database</span></span>
            <span className="h1-mask"><span className="h1-line h1-accent" ref={h1Line2}>like a human.</span></span>
          </h1>
          <p className="hero-sub" ref={subEl}>No SQL required. Ask questions in plain English, get instant answers, and trust the logic with our verifiable AI engine.</p>
          <div className="hero-ctas" ref={ctaRow}>
            <button className="btn btn-primary btn-lg" data-testid="hero-start-free-button" onClick={() => { trackCtaClick("hero", "Start for free", "/signup"); window.dispatchEvent(new CustomEvent("bolodb:open-auth", { detail: { mode: "signup" } })); }}>
              Start for free
            </button>
            <button className="btn btn-ghost btn-lg" data-testid="hero-demo-button" onClick={() => { trackCtaClick("hero", "Watch it work", "#demo"); scrollTo("demo"); }}>
              Watch it work
            </button>
          </div>
        </div>
        <div className="hero-side" ref={trustEl}>
          <div className="trust-card">
            <span className="trust-label">Works with</span>
            <div className="db-logos">
              <span className="db-logo">PostgreSQL</span>
              <span className="db-logo">MySQL</span>
              <span className="db-logo">SQL Server</span>
              <span className="db-logo">SQLite</span>
            </div>
            <span className="trust-line">read-only · your data stays yours</span>
          </div>
        </div>
      </div>
    </section>
  );
}
