// frontend/src/lib/marketing/MarketingNav.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { appState } from "$lib/appState.svelte";
  import { scrollTo } from "$lib/motion/lenis";
  import { trackCtaClick, trackThemeToggle } from "$lib/marketing/analytics";
  import Logo from "../components/ui/Logo.svelte";

  const navLinks = [
    { label: "Demo", href: "#demo" },
    { label: "How it works", href: "#pipeline" },
    { label: "Trust", href: "#trust" },
    { label: "Connect", href: "#integrations" },
  ];

  let condensed = $state(false);

  $effect(() => {
    if (typeof window === "undefined") return;
    function onScroll() {
      const hero = document.getElementById("hero");
      if (!hero) { condensed = window.scrollY > 300; return; }
      condensed = window.scrollY >= hero.offsetTop + hero.offsetHeight - 100;
    }
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  });

  function handleThemeToggle() {
    const before = appState.theme;
    appState.toggleTheme();
    trackThemeToggle(appState.theme);
  }

  function navScrollTo(href: string) {
    scrollTo(href.slice(1));
  }
</script>

<nav class="marketing-nav" class:condensed>
  <div class="nav-inner">
    <button class="nav-logo" onclick={() => scrollTo("hero")}>
      <Logo size={22} sub={false} />
    </button>

    <div class="nav-links">
      {#each navLinks as link}
        <button class="nav-link" onclick={() => navScrollTo(link.href)}>
          {link.label}
        </button>
      {/each}
    </div>

    <div class="nav-right">
      <button class="theme-toggle" onclick={handleThemeToggle} aria-label="Toggle Theme">
        {#if appState.theme === "dark"}
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
          </svg>
        {:else}
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
          </svg>
        {/if}
      </button>
      <button class="btn btn-ghost btn-sm" onclick={() => { trackCtaClick("nav", "Log in", "/login"); goto("/login"); }}>Log in</button>
      <button class="btn btn-primary btn-sm" onclick={() => { trackCtaClick("nav", "Start free", "/signup"); goto("/signup"); }}>Start free</button>
    </div>
  </div>
</nav>

<style>
  .marketing-nav {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 1000;
    height: 72px;
    display: flex;
    align-items: center;
    padding: 0 24px;
    background: color-mix(in srgb, var(--surface) 60%, transparent);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    border-bottom: 1px solid var(--border-2);
    transition: height 0.3s var(--ease), box-shadow 0.3s var(--ease);
  }

  .marketing-nav.condensed {
    height: 60px;
    box-shadow: var(--shadow);
  }

  .nav-inner {
    max-width: 1100px;
    width: 100%;
    margin: 0 auto;
    display: flex;
    align-items: center;
  }

  .nav-logo {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: flex-start;
    background: none;
    border: none;
    cursor: pointer;
    padding: 0;
    border-radius: 8px;
  }
  .nav-logo:focus-visible {
    outline: none;
    box-shadow: 0 0 0 4px var(--ring);
  }

  .nav-links {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 4px;
    flex: 1;
  }

  @media (max-width: 640px) {
    .nav-links { display: none; }
  }

  .nav-link {
    background: none;
    border: none;
    padding: 6px 14px;
    font-size: 13.5px;
    font-weight: 500;
    color: var(--muted);
    border-radius: 8px;
    transition: color 0.15s, background 0.15s;
    cursor: pointer;
  }

  .nav-link:hover {
    color: var(--ink);
    background: var(--surface-2);
  }
  .nav-link:focus-visible {
    outline: none;
    box-shadow: 0 0 0 4px var(--ring);
  }

  .nav-right {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 8px;
  }

  .theme-toggle {
    background: transparent;
    border: none;
    color: var(--muted);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 8px;
    border-radius: 50%;
    transition: all 0.15s;
    cursor: pointer;
  }

  .theme-toggle:hover {
    color: var(--ink);
    background: var(--surface-2);
  }
  .theme-toggle:focus-visible {
    outline: none;
    box-shadow: 0 0 0 4px var(--ring);
  }


</style>

// next/src/components/marketing/marketing-nav.tsx
"use client";

import { useEffect, useState } from "react";
import { appState, useAppState } from "@/lib/app-state";
import { scrollTo, getLenis } from "@/lib/motion/lenis";
import { trackCtaClick, trackThemeToggle } from "@/lib/marketing/analytics";

const navLinks = [
  { label: "Demo", href: "#demo" },
  { label: "How it works", href: "#pipeline" },
  { label: "Trust", href: "#trust" },
];

export function MarketingNav() {
  const state = useAppState();
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") return;

    function checkScroll() {
      const lenis = getLenis();
      const scrollY = lenis ? lenis.scroll : window.scrollY;
      setVisible(scrollY > 200);
    }

    checkScroll();

    const lenis = getLenis();
    if (lenis) {
      const unsub = lenis.on("scroll", checkScroll);
      return () => unsub();
    } else {
      window.addEventListener("scroll", checkScroll, { passive: true });
      return () => window.removeEventListener("scroll", checkScroll);
    }
  }, []);

  function handleThemeToggle() {
    appState.toggleTheme();
    trackThemeToggle(state.theme);
  }

  function navScrollTo(href: string) {
    scrollTo(href.slice(1));
  }

  return (
    <nav className={"pill-nav" + (visible ? " visible" : "")} aria-label="Main navigation">
      <div className="pill">
        <button className="pill-logo" onClick={() => scrollTo("hero")} aria-label="BoloDB — Scroll to top">
          <svg width="18" height="18" viewBox="0 0 256 256" fill="none">
            <path d="M 52 44 Q 52 30 66 30 L 190 30 Q 204 30 204 44 L 204 138 Q 204 152 190 152 L 116 152 L 88 176 L 92 152 L 66 152 Q 52 152 52 138 Z" stroke="currentColor" strokeWidth="6" fill="none" />
            <g stroke="currentColor" strokeWidth="6" strokeLinecap="round" fill="none">
              <ellipse cx="128" cy="66" rx="34" ry="11" />
              <path d="M 94 66 L 94 108 Q 94 119 128 119 Q 162 119 162 108 L 162 66" />
              <path d="M 94 87 Q 94 98 128 98 Q 162 98 162 87" />
            </g>
            <circle cx="182" cy="46" r="3.5" fill="currentColor" />
          </svg>
        </button>

        <div className="pill-divider"></div>

        <div className="pill-links">
          {navLinks.map((link) => (
            <button key={link.href} className="pill-link" onClick={() => navScrollTo(link.href)}>
              {link.label}
            </button>
          ))}
        </div>

        <div className="pill-divider"></div>

        <div className="pill-actions">
          <button className="theme-toggle" data-testid="nav-theme-toggle" onClick={handleThemeToggle} aria-label="Toggle Theme">
            {state.theme === "dark" ? (
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
              </svg>
            ) : (
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
              </svg>
            )}
          </button>
          <button className="btn btn-ghost btn-sm" data-testid="nav-login-button" onClick={() => { trackCtaClick("nav", "Log in", "/login"); window.dispatchEvent(new CustomEvent("bolodb:open-auth", { detail: { mode: "login" } })); }}>Log in</button>
          <button className="btn btn-primary btn-sm" data-testid="nav-signup-button" onClick={() => { trackCtaClick("nav", "Start free", "/signup"); window.dispatchEvent(new CustomEvent("bolodb:open-auth", { detail: { mode: "signup" } })); }}>Start free</button>
        </div>
      </div>
    </nav>
  );
}
