// frontend/src/routes/auth/callback/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { goto } from "$app/navigation";
  import { supabaseGoogleLogin } from "$lib/api";

  let error = $state("");
  let processing = $state(true);

  onMount(async () => {
    try {
      const hash = window.location.hash;
      const params = new URLSearchParams(hash.substring(1));

      const errorParam = params.get("error");
      const errorDescription = params.get("error_description");
      const accessToken = params.get("access_token");
      if (!accessToken) {
        error =
          errorDescription || errorParam || "No access token received from Supabase";
        processing = false;
        return;
      }

      await supabaseGoogleLogin(accessToken);
      window.location.hash = "";
      goto("/chat");
    } catch (err: any) {
      error = err.message || "Authentication failed";
      processing = false;
    }
  });
</script>

<div
  style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;padding:20px"
>
  {#if error}
    <div
      style="padding:16px 24px;background:#FFF8ED;border:1px solid #F5D78A;border-radius:8px;color:#7A5C0A;font-size:14px;max-width:400px;text-align:center"
    >
      <p style="margin:0 0 12px">{error}</p>
      <a
        href="/"
        style="color:#2563EB;text-decoration:underline;cursor:pointer"
      >
        Back to login
      </a>
    </div>
  {:else}
    <div style="text-align:center;color:var(--ink-muted);font-size:14px">
      <div
        style="width:24px;height:24px;border:2px solid var(--border);border-top-color:var(--accent);border-radius:50%;animation:spin 0.8s linear infinite;margin:0 auto 12px"
      ></div>
      Signing you in...
    </div>
  {/if}
</div>

<style>
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>

// next/src/app/auth/callback/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { supabaseGoogleLogin } from "@/lib/api";

export default function AuthCallbackPage() {
  const router = useRouter();
  const [error, setError] = useState("");
  const [processing, setProcessing] = useState(true);

  useEffect(() => {
    async function handleCallback() {
      try {
        const hash = window.location.hash;
        const params = new URLSearchParams(hash.substring(1));

        const errorParam = params.get("error");
        const errorDescription = params.get("error_description");
        const accessToken = params.get("access_token");

        if (!accessToken) {
          setError(
            errorDescription || errorParam || "No access token received from Supabase",
          );
          setProcessing(false);
          return;
        }

        await supabaseGoogleLogin(accessToken);
        window.location.hash = "";
        router.push("/chat");
      } catch (err: any) {
        setError(err.message || "Authentication failed");
        setProcessing(false);
      }
    }

    handleCallback();
  }, [router]);

  return (
    <div className="auth-page">
      <div className="card rise auth-card">
        <div className="auth-header">
          <div className="auth-logo-wrap">
            <Link href="/" className="text-2xl font-bold">BoloDB</Link>
          </div>
          {error ? (
            <>
              <h1 className="auth-title">Authentication failed</h1>
              <p className="auth-subtitle">Something went wrong during sign-in.</p>
            </>
          ) : (
            <>
              <h1 className="auth-title">Signing you in</h1>
              <p className="auth-subtitle">Please wait while we complete your authentication.</p>
            </>
          )}
        </div>

        {error ? (
          <>
            <div role="alert" aria-live="polite" className="auth-error" data-testid="callback-error">
              {error}
            </div>
            <div className="auth-footer">
              <Link href="/login">&larr; Back to sign in</Link>
            </div>
          </>
        ) : (
          <div style={{ textAlign: "center", padding: "24px 0" }}>
            <span className="spinner" />
          </div>
        )}
      </div>
    </div>
  );
}
